package com.osporo.engine.shared.enums;

public enum ErrorCode {

    // Auth
    AUTHENTICATION_FAILED,
    EMAIL_ALREADY_EXISTS,
    INVALID_TOKEN,
    ACCOUNT_SUSPENDED,

    // User
    PROFILE_NOT_FOUND,
    USER_ALREADY_SUSPENDED,
    USER_NOT_SUSPENDED,
    ROLE_HIERARCHY_VIOLATION,
    ROLE_EXCEEDS_CALLER_PERMISSIONS,
    INVALID_ROLE_FILTER,
    ACTIVE_ORDERS_EXIST,

    // Tenant
    TENANT_NOT_FOUND,
    TENANT_SUSPENDED,
    TENANT_CONTEXT_MISSING,
    UNSUPPORTED_PAYMENT_PROVIDER,
    ROLE_NOT_FOUND,
    ROLE_NAME_EXISTS,
    ROLE_HAS_ACTIVE_USERS,
    CANNOT_MODIFY_SYSTEM_ROLE,
    INVALID_PERMISSION_BUNDLE,

    // Category
    CATEGORY_NOT_FOUND,
    CATEGORY_SLUG_EXISTS,
    CATEGORY_ALREADY_ACTIVE,
    CATEGORY_ALREADY_INACTIVE,
    CATEGORY_HAS_ACTIVE_LISTINGS,

    // Listing
    LISTING_NOT_FOUND,
    LISTING_NOT_EDITABLE,
    LISTING_ALREADY_ACTIVE,
    LISTING_ALREADY_DRAFT,
    LISTING_ALREADY_SOLD,
    LISTING_ALREADY_TAKEN_DOWN,
    LISTING_HAS_ACTIVE_ORDER,
    LISTING_MISSING_REQUIRED_ATTRIBUTES,
    LISTING_MISSING_IMAGES,
    INVALID_LISTING_TYPE,
    INVALID_ATTRIBUTE,
    IMAGE_NOT_FOUND,
    IMAGE_LIMIT_EXCEEDED,
    IMAGE_ID_MISMATCH,
    INVALID_PARAMETER,

    // Order
    ORDER_NOT_FOUND,
    CANNOT_ORDER_OWN_LISTING,
    INVALID_DELIVERY_METHOD,
    SELLER_NOT_ONBOARDED,
    INVALID_ORDER_TRANSITION,
    ORDER_ALREADY_CANCELLED,
    ORDER_ALREADY_REFUNDED,
    REFUND_NOT_ELIGIBLE,

    // Payment
    SELLER_ALREADY_ONBOARDED,
    PAYMENT_FAILED,
    CHECKOUT_EXPIRED,
    PAYOUT_FAILED,

    // Escrow
    ESCROW_NOT_FOUND,
    ESCROW_ALREADY_RELEASED,
    ESCROW_ALREADY_REFUNDED,

    // Messaging
    THREAD_NOT_FOUND,
    MESSAGE_BLOCKED,
    CANNOT_MESSAGE_SELF,
    PARTICIPANT_SUSPENDED,

    // Moderation
    MODERATION_ITEM_NOT_FOUND,
    MODERATION_ITEM_ALREADY_REVIEWED,
    INVALID_FILTER_RULE,
    REPORT_ALREADY_SUBMITTED,

    // General
    INSUFFICIENT_PERMISSIONS,
    VALIDATION_ERROR,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_SERVER_ERROR
}